--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS challenge;
--
-- Name: challenge; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE challenge WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Mexico.1252';


ALTER DATABASE challenge OWNER TO postgres;

\connect challenge

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    account_number character varying(255),
    client_id bigint,
    initial_balance double precision,
    status boolean,
    account_type character varying(255)
);


ALTER TABLE public.account OWNER TO postgres;

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    status boolean NOT NULL,
    identification character varying(255) NOT NULL
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- Name: movement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movement (
    id bigint NOT NULL,
    balance double precision NOT NULL,
    date date NOT NULL,
    movement_type character varying(255) NOT NULL,
    value double precision NOT NULL,
    accountid bigint NOT NULL
);


ALTER TABLE public.movement OWNER TO postgres;

--
-- Name: movement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    address character varying(255),
    gender character varying(255),
    identification character varying(255) NOT NULL,
    name character varying(255),
    phone character varying(255)
);


ALTER TABLE public.person OWNER TO postgres;

--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.account (id, account_number, client_id, initial_balance, status, account_type) VALUES (7, '585545', 1, 1000, true, 'CORRIENTE');
INSERT INTO public.account (id, account_number, client_id, initial_balance, status, account_type) VALUES (1, '478758', 1, 1425, true, 'AHORROS');
INSERT INTO public.account (id, account_number, client_id, initial_balance, status, account_type) VALUES (2, '225487', 2, 700, true, 'CORRIENTE');
INSERT INTO public.account (id, account_number, client_id, initial_balance, status, account_type) VALUES (3, '495878', 3, 150, true, 'AHORROS');
INSERT INTO public.account (id, account_number, client_id, initial_balance, status, account_type) VALUES (4, '496825', 2, 0, true, 'AHORROS');
INSERT INTO public.account (id, account_number, client_id, initial_balance, status, account_type) VALUES (5, '496848', 4, 4460, true, 'AHORROS');


--
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.customer (id, password, status, identification) VALUES (1, '1234', true, '1234567890');
INSERT INTO public.customer (id, password, status, identification) VALUES (2, '5678', true, '1234567891');
INSERT INTO public.customer (id, password, status, identification) VALUES (3, '1245', true, '1234567892');
INSERT INTO public.customer (id, password, status, identification) VALUES (4, '1245', true, '172605');
INSERT INTO public.customer (id, password, status, identification) VALUES (6, 'test123', true, '9999999999');


--
-- Data for Name: movement; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.movement (id, balance, date, movement_type, value, accountid) VALUES (1, 1425, '2025-07-30', 'DEBITO', 575, 1);
INSERT INTO public.movement (id, balance, date, movement_type, value, accountid) VALUES (2, 700, '2025-07-30', 'CREDITO', 600, 2);
INSERT INTO public.movement (id, balance, date, movement_type, value, accountid) VALUES (3, 150, '2025-07-30', 'CREDITO', 150, 3);
INSERT INTO public.movement (id, balance, date, movement_type, value, accountid) VALUES (4, 0, '2025-07-30', 'DEBITO', 540, 4);
INSERT INTO public.movement (id, balance, date, movement_type, value, accountid) VALUES (5, 4460, '2025-07-30', 'DEBITO', 540, 5);


--
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.person (id, address, gender, identification, name, phone) VALUES (1, 'Otavalo sn y principal', 'M', '1234567890', 'Jose Lema', '098254785');
INSERT INTO public.person (id, address, gender, identification, name, phone) VALUES (2, 'Amazonas y NNUU', 'F', '1234567891', 'Marianela Montalvo', '097548965');
INSERT INTO public.person (id, address, gender, identification, name, phone) VALUES (3, '13 junio y Equinoccial', 'M', '1234567892', 'Juan Osorio', '098874587');
INSERT INTO public.person (id, address, gender, identification, name, phone) VALUES (4, '13 junio y Equinoccial', 'M', '172605', 'Juan Sebastian', '098874587');
INSERT INTO public.person (id, address, gender, identification, name, phone) VALUES (6, 'Karate Street', 'M', '9999999999', 'Karate Tester', '123456789');


--
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 7, true);


--
-- Name: movement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movement_id_seq', 5, true);


--
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 6, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- Name: movement movement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: person uk4r2cs4eybw7joyi0u8v7vywhg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT uk4r2cs4eybw7joyi0u8v7vywhg UNIQUE (identification);


--
-- Name: movement fkoemeananv9w9qnbcoccbl70a0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT fkoemeananv9w9qnbcoccbl70a0 FOREIGN KEY (accountid) REFERENCES public.account(id);


--
-- Name: customer fkr9okrktxscw3omxi1wm7cg18u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fkr9okrktxscw3omxi1wm7cg18u FOREIGN KEY (identification) REFERENCES public.person(identification);


--
-- PostgreSQL database dump complete
--

